apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: layer8-production
resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
patches:
  - path: api-deployment-patch.yaml
  - path: worker-deployment-patch.yaml
images:
  - name: ghcr.io/robs46859-eng/layer8
    newTag: v0.1.0
